import os
from pyray import *

# --- CONFIGURATION FENETRE ---
SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 1024
TITLE = "Map Editor - Python/Raylib 1870"
FPS = 60

# --- CONFIGURATION UI ---
PANEL_RIGHT_WIDTH = 300
PANEL_BOTTOM_HEIGHT = 150
VIEW_WIDTH = SCREEN_WIDTH - PANEL_RIGHT_WIDTH
VIEW_HEIGHT = SCREEN_HEIGHT - PANEL_BOTTOM_HEIGHT

# --- FICHIERS ---
RESOURCE_DIR = "Ressource"
SAVED_DIR = "saved"
IMAGE_FILENAME = "CarteNord1870.png"
IMAGE_PATH = os.path.join(RESOURCE_DIR, IMAGE_FILENAME)

# --- NAVIGATION ---
SCROLL_SPEED = 5

# --- CONSTANTES D'ETATS ---
MODE_EDITION = 0
MODE_TEST = 1

TEST_SUB_INSPEC = 0
TEST_SUB_MANUAL = 1
TEST_SUB_AUTO = 2

# --- OUTILS ---
TOOL_NODE = 0
TOOL_EDGE = 1
TOOL_DELETE = 2

# --- FORMES ---
SHAPE_CIRCLE = 0
SHAPE_RECT = 1

# --- CONFIGURATION VOIES ---
HANDLE_SIZE = 12

EDGE_TYPE_COLORS = {
    1: GRAY, 2: BLACK, 3: BROWN, 4: BLUE, 5: DARKBLUE,
    6: ORANGE, 7: RED, 8: DARKGREEN, 9: PURPLE, 10: GOLD,
    11: MAROON, 12: LIME, 13: PINK, 14: SKYBLUE, 15: VIOLET
}
DEFAULT_EDGE_COLOR = LIGHTGRAY

# --- COULEURS UI ---
BG_COLOR = DARKBLUE
UI_BG_COLOR = BLACK
UI_BORDER_COLOR = DARKGRAY
TEXT_COLOR = WHITE
LOG_COLOR = GREEN
COORD_COLOR = RED
GHOST_COLOR = BLACK
NODE_EDIT_COLOR = BLUE
DELETE_COLOR = RED
SELECTION_COLOR = ORANGE
START_NODE_COLOR = GREEN

# Couleur CYAN définie explicitement
CYAN = Color(0, 255, 255, 255)